version: '3'
services:
  web:
    build: ./web-app
    ports:
      - "3000:3000"
  db:
    build: ./postgresql
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
